version: "3.7"
services:
  frontend:
    image: zorro909/blankdiscordbot:${TAG}
    volumes:
     - blankBotConfig:/blankbot/config
    networks:
     - blank-bot-bridge
    environment:
      MYSQL_HOST: jdbc://mysql:3306
      MYSQL_HOSTNAME: mysql:3306
      MYSQL_DATABASE: blankbot
      MYSQL_USERNAME: blankbot
      MYSQL_PASSWORD: blankbot
      DISCORD_AUTH_TOKEN:
      DISCORD_GUILD_ID:
      SPRING_CONFIG:
  mysql:
    image: "mariadb"
    environment:
      MYSQL_DATABASE: blankbot
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: blankbot
      MYSQL_PASSWORD: blankbot
    networks:
      - blank-bot-bridge
    volumes:
      - blankBotMysqlData:/var/lib/mysql
networks:
  blank-bot-bridge:
    driver: bridge
volumes:
  blankBotMysqlData:
  blankBotConfig:
