version: "3.7"
services:
  frontend:
    image: zorro909/blankdiscordbot:${TAG}
    volumes:
     - blankBotConfig:/blankbot/config
    networks:
     - blank-bot-bridge
    environment:
      MYSQL_HOST: jdbc:mysql://mysql:3306
      MYSQL_HOSTNAME: mysql:3306
      MYSQL_DATABASE: blankbot
      MYSQL_USERNAME: blankbot
      MYSQL_PASSWORD: blankbot
      DISCORD_AUTH_TOKEN: ${DISCORD_AUTH_TOKEN}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
    entrypoint: /bin/sh
    command: -c 'curl -o config/application.yml $SPRING_CONFIG && ./wait-for-it.sh mysql:3306 -- java -jar BlankDiscordBot.jar -Dspring.config.location=config/application.yml'
  mysql:
    image: "mariadb"
    environment:
      MYSQL_DATABASE: blankbot
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: blankbot
      MYSQL_PASSWORD: blankbot
    networks:
      - blank-bot-bridge
    volumes:
      - blankBotMysqlData:/var/lib/mysql
networks:
  blank-bot-bridge:
    driver: bridge
volumes:
  blankBotMysqlData:
  blankBotConfig:
